#Plasmo Voice Changer preset
#Wed Jul 22 01:10:37 ART 2026
autotuneKey=0
autotuneMix=0.0
autotuneScale=0
autotuneStrength=0.6
bitDepth=16.0
distortion=0.0
echoDelayMs=120
echoFeedback=0.1
echoMix=0.0
enabled=false
formant=1.0
gain=1.0
highEq=0.0
lowEq=0.0
midEq=0.0
mix=0.9
noise=0.0
pitch=1.0
preset=CUSTOM
robotFrequency=60
robotMix=0.0
savedPresetName=
selfListen=false
strength=100
tremoloDepth=0.0
tremoloRate=2.5
